services:
  lint:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: malnati-ops-eslint:latest
    volumes:
      - ${PROJECT_PATH:-.}:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    command: ["--fix", "."]
